display_name: PDF Splitter
msix_version: 2.1.1.1
certificate_path: C:\dev\pdf_splitter\app_regeomaria_net.pfx
certificate_password: 34v3M4r14
logo_path: c:\dev\pdf_splitter\assets\icon.png
#Certificato da inserire tra le Autorità root di certificazione attendibili
