display_name: PDF Splitter
msix_version: 2.2.0.1
certificate_path: C:\Users\massimo.travascio\Develop\pdf_splitter\app_regeomaria_net.pfx
certificate_password: 34v3M4ri4
logo_path: C:\Users\massimo.travascio\Develop\pdf_splitter\assets\icon.png
#Certificato da inserire tra le Autorità root di certificazione attendibili
